##########################################
############# Install Nginx ##############
##########################################

---
- name: Install Nginx web server
  hosts: all
  become: yes
  vars:
    domain_name1          : sbabanin2.devops.rebrain.srwx.net
    certbot_admin_email   : sergeybabanin@yandex.ru
    letsencrypt_ssl_dir   : /etc/letsencrypt/live
    index                 : /roles/deploy_nginx/templates
    index1                : index.site1.html
    root_directory        : /usr/share/nginx/html/
    worker_processes      : 1
    worker_connections    : 1024
    nginx_log_dir         : "/var/log/nginx"
    nginx_access_log_name : "access.log"
    nginx_error_log_name  : "error.log"

    nginx_http_params:
      sendfile            : "on"
      tcp_nopush          : "on"
      tcp_nodelay         : "off"
      keepalive_timeout   : "65"
      gzip                : "on"
  roles: 
    - deploy_nginx
    - letsencrypt
    - virtual_host
